In [1]:
import pandas as pd
import numpy as np

In [2]:
wetchem_df = pd.read_csv("all_wetchem_data_uncleeaned_15-7-2022 (1).csv")
hv_outliers_df = pd.read_csv("outputFiles/hv_outliers.csv")
lv_outliers_df = pd.read_csv("outputFiles/lv_outliers.csv")
resid_outliers_df = pd.read_csv("outputFiles/residual_outliers_filtered_out.csv")
cooks_outliers_df = pd.read_csv("outputFiles/outliers_cooks_distance.csv")

In [3]:
hv_outliers_df

,sample_code,organic_carbon,total_nitrogen,aluminium,boron,calcium,copper,ec_salts,exchangeable_acidity,iron,...,potassium,sodium,sulphur,zinc,cec,clay,sand,silt,phosphorus_olsen,reactive_carbon
0,AGD207-408PA0086,NaN,NaN,NaN,30.70,1.83,4.07,NaN,NaN,127.0,...,4.01,285.0,0.40,17.20,NaN,NaN,NaN,NaN,NaN,NaN
1,CA028CM0028,NaN,NaN,NaN,80.30,1.24,37.50,2.57,NaN,NaN,...,1.20,NaN,0.30,126.00,NaN,NaN,NaN,NaN,NaN,NaN
2,CA028PA0454,NaN,NaN,NaN,155.00,0.48,2.88,NaN,NaN,158.0,...,1.00,53.8,0.17,11.50,NaN,NaN,NaN,NaN,NaN,NaN
3,CA052CM0028,NaN,NaN,NaN,75.20,2.39,59.10,18.80,NaN,NaN,...,4.69,1860.0,0.60,142.00,NaN,NaN,NaN,NaN,NaN,NaN
4,CA053SA1093,NaN,NaN,NaN,0.93,4260.00,1.30,54.30,NaN,226.0,...,578.00,107.0,15.50,222.00,32.700000,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
356,FA503-138SA0001,NaN,NaN,NaN,1.96,3720.00,1.82,2530.00,NaN,112.0,...,2970.00,225.0,406.00,49.20,38.867250,NaN,NaN,NaN,NaN,NaN
357,FA611-14SA0009,NaN,NaN,NaN,2.60,NaN,4.08,4500.00,NaN,205.0,...,457.00,1790.0,NaN,4.62,NaN,NaN,NaN,NaN,NaN,NaN
358,FA616-200SA0001,NaN,NaN,NaN,3.82,NaN,2.48,4800.00,NaN,140.0,...,NaN,257.0,204.00,4.44,NaN,NaN,NaN,NaN,NaN,NaN
359,FA806-248SA0001,NaN,NaN,NaN,2.08,3020.00,0.91,440.00,NaN,227.0,...,2940.00,88.4,53.80,18.70,29.147452,NaN,NaN,NaN,NaN,NaN
360,FA807-142SA0001,NaN,NaN,NaN,3.82,3070.00,1.85,4590.00,NaN,342.0,...,2240.00,199.0,109.00,12.90,31.385705,NaN,NaN,NaN,NaN,NaN

In [4]:
lv_outliers_df

,sample_code,organic_carbon,total_nitrogen,aluminium,boron,calcium,copper,ec_salts,exchangeable_acidity,iron,...,potassium,sodium,sulphur,zinc,cec,clay,sand,silt,phosphorus_olsen,reactive_carbon
0,AGD207-408PA0086,NaN,NaN,NaN,30.70,1.83,4.07,NaN,NaN,127.0,...,4.01,285.0,0.40,17.20,NaN,NaN,NaN,NaN,NaN,NaN
1,CA028CM0028,NaN,NaN,NaN,80.30,1.24,37.50,2.57,NaN,NaN,...,1.20,NaN,0.30,126.00,NaN,NaN,NaN,NaN,NaN,NaN
2,CA028PA0454,NaN,NaN,NaN,155.00,0.48,2.88,NaN,NaN,158.0,...,1.00,53.8,0.17,11.50,NaN,NaN,NaN,NaN,NaN,NaN
3,CA052CM0028,NaN,NaN,NaN,75.20,2.39,59.10,18.80,NaN,NaN,...,4.69,1860.0,0.60,142.00,NaN,NaN,NaN,NaN,NaN,NaN
4,CA266PA0681,NaN,NaN,NaN,161.00,0.77,51.40,NaN,NaN,99.5,...,2.19,NaN,0.31,29.70,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
140,CW017SA20572,NaN,NaN,1370.0,0.12,770.00,2.61,30.90,NaN,41.1,...,72.50,49.7,20.20,0.21,8.397823,NaN,NaN,NaN,NaN,NaN
141,CW017SA20678,NaN,NaN,2130.0,0.27,896.00,1.40,42.40,0.3,78.8,...,148.00,15.0,14.70,0.60,10.023617,NaN,NaN,NaN,NaN,NaN
142,CW070SA0017,NaN,NaN,NaN,0.90,3120.00,1.05,239.00,NaN,131.0,...,3070.00,535.0,62.60,16.00,32.744242,NaN,NaN,NaN,60.4,NaN
143,CZ09SA0027,NaN,NaN,NaN,0.14,664.00,0.96,1070.00,NaN,150.0,...,1470.00,54.9,883.00,11.20,16.472902,NaN,NaN,NaN,NaN,NaN
144,FA616-200SA0001,NaN,NaN,NaN,3.82,NaN,2.48,4800.00,NaN,140.0,...,NaN,257.0,204.00,4.44,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
resid_outliers_df

,sample_code,index,organic_carbon,total_nitrogen,aluminium,boron,calcium,copper,ec_salts,exchangeable_acidity,...,potassium,sodium,sulphur,zinc,cec,clay,sand,silt,phosphorus_olsen,reactive_carbon
0,AGD102-129SA0001,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,646.0,169.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,AGD102-130SA0001,1,NaN,NaN,NaN,2.89,1990.0,1.25,86.0,NaN,...,387.0,112.0,NaN,24.80,15.074521,NaN,NaN,NaN,NaN,NaN
2,AGD102-132SA0001,2,NaN,NaN,NaN,NaN,2850.0,NaN,NaN,NaN,...,208.0,218.0,NaN,NaN,26.810968,NaN,NaN,NaN,NaN,NaN
3,AGD102-134SA0001,5,NaN,NaN,NaN,NaN,431.0,NaN,NaN,NaN,...,44.2,27.8,NaN,NaN,8.335421,NaN,NaN,NaN,NaN,NaN
4,AGD102-136SA0001,7,NaN,NaN,NaN,NaN,954.0,NaN,NaN,NaN,...,168.0,27.6,NaN,NaN,12.018632,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
47775,I48-1-100SA0001,121929,NaN,NaN,NaN,0.39,1570.0,4.96,59.1,NaN,...,141.0,84.2,12.1,1.85,20.779947,NaN,NaN,NaN,NaN,NaN
47776,I48-1-101SA0001,121930,NaN,NaN,NaN,1.28,3990.0,4.64,50.3,NaN,...,2040.0,97.9,20.2,2.42,31.221755,NaN,NaN,NaN,NaN,NaN
47777,I48-1-105SA0003,121931,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,17.7,NaN
47778,I48-1-108SA0001,121932,NaN,NaN,NaN,0.37,NaN,1.56,136.0,NaN,...,40.9,36.7,61.6,0.66,NaN,NaN,NaN,NaN,NaN,NaN
47779,I48-1-109SA0001,121933,NaN,NaN,NaN,3.52,NaN,0.75,460.0,NaN,...,65.0,101.0,183.0,0.50,29.226475,NaN,NaN,NaN,49.8,NaN

In [6]:
cooks_outliers_df

,sample_code,organic_carbon,total_nitrogen,aluminium,boron,calcium,copper,ec_salts,exchangeable_acidity,iron,...,potassium,sodium,sulphur,zinc,cec,clay,sand,silt,phosphorus_olsen,reactive_carbon
0,AGD102-129SA0001,NaN,NaN,NaN,NaN,5730.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,40.065624,NaN,NaN,NaN,NaN,NaN
1,AGD102-132SA0001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,AGD102-144SA0001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,AGD102-57SA0001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,164.0,NaN
4,AGD103-40SA0001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20589,I48-1-39SA0001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,72.2,NaN
20590,I48-1-41SA0001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,79.2,NaN
20591,I48-1-42SA0001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,71.6,NaN
20592,I48-1-58SA0001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,138.0,NaN
20593,I48-1-99SA0001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,69.6,NaN

In [7]:
wetchem_df = wetchem_df.rename(columns={"Unnamed: 0":"sample_code"})

In [8]:
# Handle the HV Outliers
hv_outliers_df_2 = hv_outliers_df.set_index("sample_code").isna()

In [9]:
hv_outliers_df_2.replace(True, np.nan, inplace=True)
hv_outliers_df_2.replace(False, 1, inplace=True)

In [10]:
hv_outliers_df_2

,organic_carbon,total_nitrogen,aluminium,boron,calcium,copper,ec_salts,exchangeable_acidity,iron,magnesium,...,potassium,sodium,sulphur,zinc,cec,clay,sand,silt,phosphorus_olsen,reactive_carbon
sample_code,,,,,,,,,,,,,,,,,,,,,
AGD207-408PA0086,NaN,NaN,NaN,1.0,1.0,1.0,NaN,NaN,1.0,1.0,...,1.0,1.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN
CA028CM0028,NaN,NaN,NaN,1.0,1.0,1.0,1.0,NaN,NaN,1.0,...,1.0,NaN,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN
CA028PA0454,NaN,NaN,NaN,1.0,1.0,1.0,NaN,NaN,1.0,1.0,...,1.0,1.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN
CA052CM0028,NaN,NaN,NaN,1.0,1.0,1.0,1.0,NaN,NaN,1.0,...,1.0,1.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN
CA053SA1093,NaN,NaN,NaN,1.0,1.0,1.0,1.0,NaN,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
FA503-138SA0001,NaN,NaN,NaN,1.0,1.0,1.0,1.0,NaN,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN
FA611-14SA0009,NaN,NaN,NaN,1.0,NaN,1.0,1.0,NaN,1.0,NaN,...,1.0,1.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN
FA616-200SA0001,NaN,NaN,NaN,1.0,NaN,1.0,1.0,NaN,1.0,NaN,...,NaN,1.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN
FA806-248SA0001,NaN,NaN,NaN,1.0,1.0,1.0,1.0,NaN,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN
FA807-142SA0001,NaN,NaN,NaN,1.0,1.0,1.0,1.0,NaN,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN

In [11]:
# Handle lv outliers
lv_outliers_df_2 = lv_outliers_df.set_index("sample_code").isna()   

lv_outliers_df_2.replace(True, np.nan, inplace=True)
lv_outliers_df_2.replace(False, 2, inplace=True)

In [12]:
lv_outliers_df_2

,organic_carbon,total_nitrogen,aluminium,boron,calcium,copper,ec_salts,exchangeable_acidity,iron,magnesium,...,potassium,sodium,sulphur,zinc,cec,clay,sand,silt,phosphorus_olsen,reactive_carbon
sample_code,,,,,,,,,,,,,,,,,,,,,
AGD207-408PA0086,NaN,NaN,NaN,2.0,2.0,2.0,NaN,NaN,2.0,2.0,...,2.0,2.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN
CA028CM0028,NaN,NaN,NaN,2.0,2.0,2.0,2.0,NaN,NaN,2.0,...,2.0,NaN,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN
CA028PA0454,NaN,NaN,NaN,2.0,2.0,2.0,NaN,NaN,2.0,2.0,...,2.0,2.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN
CA052CM0028,NaN,NaN,NaN,2.0,2.0,2.0,2.0,NaN,NaN,2.0,...,2.0,2.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN
CA266PA0681,NaN,NaN,NaN,2.0,2.0,2.0,NaN,NaN,2.0,2.0,...,2.0,NaN,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
CW017SA20572,NaN,NaN,2.0,2.0,2.0,2.0,2.0,NaN,2.0,2.0,...,2.0,2.0,2.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN
CW017SA20678,NaN,NaN,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,...,2.0,2.0,2.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN
CW070SA0017,NaN,NaN,NaN,2.0,2.0,2.0,2.0,NaN,2.0,2.0,...,2.0,2.0,2.0,2.0,2.0,NaN,NaN,NaN,2.0,NaN
CZ09SA0027,NaN,NaN,NaN,2.0,2.0,2.0,2.0,NaN,2.0,2.0,...,2.0,2.0,2.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN
FA616-200SA0001,NaN,NaN,NaN,2.0,NaN,2.0,2.0,NaN,2.0,NaN,...,NaN,2.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
# Handle Cook's outliers
cooks_outliers_df_2 = cooks_outliers_df.set_index("sample_code").isna()   

cooks_outliers_df_2.replace(True, np.nan, inplace=True)
cooks_outliers_df_2.replace(False, 3, inplace=True)

In [14]:
cooks_outliers_df_2

,organic_carbon,total_nitrogen,aluminium,boron,calcium,copper,ec_salts,exchangeable_acidity,iron,magnesium,...,potassium,sodium,sulphur,zinc,cec,clay,sand,silt,phosphorus_olsen,reactive_carbon
sample_code,,,,,,,,,,,,,,,,,,,,,
AGD102-129SA0001,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN,3.0,...,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN
AGD102-132SA0001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
AGD102-144SA0001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
AGD102-57SA0001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,NaN
AGD103-40SA0001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
I48-1-39SA0001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,NaN
I48-1-41SA0001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,NaN
I48-1-42SA0001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,NaN
I48-1-58SA0001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,NaN
I48-1-99SA0001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,NaN

In [15]:
# Handle Residual outliers
resid_outliers_df_2 = resid_outliers_df.set_index("sample_code").isna()   

resid_outliers_df_2.replace(True, np.nan, inplace=True)
resid_outliers_df_2.replace(False, 4, inplace=True)

In [16]:
resid_outliers_df_2

,index,organic_carbon,total_nitrogen,aluminium,boron,calcium,copper,ec_salts,exchangeable_acidity,iron,...,potassium,sodium,sulphur,zinc,cec,clay,sand,silt,phosphorus_olsen,reactive_carbon
sample_code,,,,,,,,,,,,,,,,,,,,,
AGD102-129SA0001,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
AGD102-130SA0001,4,NaN,NaN,NaN,4.0,4.0,4.0,4.0,NaN,4.0,...,4.0,4.0,NaN,4.0,4.0,NaN,NaN,NaN,NaN,NaN
AGD102-132SA0001,4,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN,...,4.0,4.0,NaN,NaN,4.0,NaN,NaN,NaN,NaN,NaN
AGD102-134SA0001,4,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN,...,4.0,4.0,NaN,NaN,4.0,NaN,NaN,NaN,NaN,NaN
AGD102-136SA0001,4,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN,...,4.0,4.0,NaN,NaN,4.0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
I48-1-100SA0001,4,NaN,NaN,NaN,4.0,4.0,4.0,4.0,NaN,4.0,...,4.0,4.0,4.0,4.0,4.0,NaN,NaN,NaN,NaN,NaN
I48-1-101SA0001,4,NaN,NaN,NaN,4.0,4.0,4.0,4.0,NaN,4.0,...,4.0,4.0,4.0,4.0,4.0,NaN,NaN,NaN,NaN,NaN
I48-1-105SA0003,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN
I48-1-108SA0001,4,NaN,NaN,NaN,4.0,NaN,4.0,4.0,NaN,4.0,...,4.0,4.0,4.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN
I48-1-109SA0001,4,NaN,NaN,NaN,4.0,NaN,4.0,4.0,NaN,4.0,...,4.0,4.0,4.0,4.0,4.0,NaN,NaN,NaN,4.0,NaN

In [17]:
wetchem_df

,sample_code,organic_carbon,total_nitrogen,aluminium,boron,calcium,copper,ec_salts,exchangeable_acidity,iron,...,potassium,sodium,sulphur,zinc,cec,clay,sand,silt,phosphorus_olsen,reactive_carbon
0,AGD102-129SA0001,NaN,NaN,NaN,NaN,5730.0,NaN,NaN,NaN,NaN,...,646.0,169.0,NaN,NaN,40.065624,NaN,NaN,NaN,NaN,NaN
1,AGD102-130SA0001,NaN,NaN,NaN,2.89,1990.0,1.25,86.0,NaN,242.0,...,387.0,112.0,NaN,24.8,15.074521,NaN,NaN,NaN,NaN,NaN
2,AGD102-132SA0001,NaN,NaN,NaN,NaN,2850.0,NaN,NaN,NaN,NaN,...,208.0,218.0,NaN,NaN,26.810968,NaN,NaN,NaN,NaN,NaN
3,AGD102-133SA0001,NaN,NaN,NaN,NaN,283.0,NaN,NaN,NaN,NaN,...,103.0,21.6,NaN,NaN,3.085441,NaN,NaN,NaN,NaN,NaN
4,AGD102-133SA0002,NaN,NaN,NaN,NaN,1320.0,NaN,NaN,NaN,NaN,...,425.0,28.0,NaN,NaN,10.690643,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
148531,CY001SA0091,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
148532,CY001SA0092,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
148533,CY002SA1001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
148534,CY002SA1002,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
148535,CY002SA1003,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [18]:
wetchem_df = wetchem_df[['sample_code']]

In [19]:
wetchem_df

             sample_code
0       AGD102-129SA0001
1       AGD102-130SA0001
2       AGD102-132SA0001
3       AGD102-133SA0001
4       AGD102-133SA0002
...                  ...
148531       CY001SA0091
148532       CY001SA0092
148533       CY002SA1001
148534       CY002SA1002
148535       CY002SA1003

[148536 rows x 1 columns]

In [20]:
outliers_df = pd.concat([hv_outliers_df_2, lv_outliers_df_2, cooks_outliers_df_2, resid_outliers_df_2], axis=0)

In [21]:
outliers_df = outliers_df.reset_index()
outliers_df

,sample_code,organic_carbon,total_nitrogen,aluminium,boron,calcium,copper,ec_salts,exchangeable_acidity,iron,...,sodium,sulphur,zinc,cec,clay,sand,silt,phosphorus_olsen,reactive_carbon,index
0,AGD207-408PA0086,NaN,NaN,NaN,1.0,1.0,1.0,NaN,NaN,1.0,...,1.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,CA028CM0028,NaN,NaN,NaN,1.0,1.0,1.0,1.0,NaN,NaN,...,NaN,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,CA028PA0454,NaN,NaN,NaN,1.0,1.0,1.0,NaN,NaN,1.0,...,1.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,CA052CM0028,NaN,NaN,NaN,1.0,1.0,1.0,1.0,NaN,NaN,...,1.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,CA053SA1093,NaN,NaN,NaN,1.0,1.0,1.0,1.0,NaN,1.0,...,1.0,1.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
68875,I48-1-100SA0001,NaN,NaN,NaN,4.0,4.0,4.0,4.0,NaN,4.0,...,4.0,4.0,4.0,4.0,NaN,NaN,NaN,NaN,NaN,4.0
68876,I48-1-101SA0001,NaN,NaN,NaN,4.0,4.0,4.0,4.0,NaN,4.0,...,4.0,4.0,4.0,4.0,NaN,NaN,NaN,NaN,NaN,4.0
68877,I48-1-105SA0003,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN,4.0
68878,I48-1-108SA0001,NaN,NaN,NaN,4.0,NaN,4.0,4.0,NaN,4.0,...,4.0,4.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,4.0
68879,I48-1-109SA0001,NaN,NaN,NaN,4.0,NaN,4.0,4.0,NaN,4.0,...,4.0,4.0,4.0,4.0,NaN,NaN,NaN,4.0,NaN,4.0

In [22]:
outliers_df = outliers_df.groupby("sample_code", sort=True).min()

In [23]:
outliers_df

,organic_carbon,total_nitrogen,aluminium,boron,calcium,copper,ec_salts,exchangeable_acidity,iron,magnesium,...,sodium,sulphur,zinc,cec,clay,sand,silt,phosphorus_olsen,reactive_carbon,index
sample_code,,,,,,,,,,,,,,,,,,,,,
AGD102-129SA0001,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN,3.0,...,4.0,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,4.0
AGD102-130SA0001,NaN,NaN,NaN,4.0,4.0,4.0,4.0,NaN,4.0,4.0,...,4.0,NaN,4.0,4.0,NaN,NaN,NaN,NaN,NaN,4.0
AGD102-132SA0001,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN,3.0,...,4.0,NaN,NaN,4.0,NaN,NaN,NaN,NaN,NaN,4.0
AGD102-134SA0001,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN,4.0,...,4.0,NaN,NaN,4.0,NaN,NaN,NaN,NaN,NaN,4.0
AGD102-136SA0001,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN,4.0,...,4.0,NaN,NaN,4.0,NaN,NaN,NaN,NaN,NaN,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
I48-1-39SA0001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,NaN,NaN
I48-1-41SA0001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,NaN,NaN
I48-1-42SA0001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,NaN,NaN
I48-1-58SA0001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,NaN,NaN
I48-1-99SA0001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,NaN,NaN

In [24]:
outliers_df = pd.merge(wetchem_df,outliers_df, on="sample_code", how="left")

In [25]:
outliers_df

,sample_code,organic_carbon,total_nitrogen,aluminium,boron,calcium,copper,ec_salts,exchangeable_acidity,iron,...,sodium,sulphur,zinc,cec,clay,sand,silt,phosphorus_olsen,reactive_carbon,index
0,AGD102-129SA0001,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN,...,4.0,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,4.0
1,AGD102-130SA0001,NaN,NaN,NaN,4.0,4.0,4.0,4.0,NaN,4.0,...,4.0,NaN,4.0,4.0,NaN,NaN,NaN,NaN,NaN,4.0
2,AGD102-132SA0001,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN,...,4.0,NaN,NaN,4.0,NaN,NaN,NaN,NaN,NaN,4.0
3,AGD102-133SA0001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,AGD102-133SA0002,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
148531,CY001SA0091,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
148532,CY001SA0092,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
148533,CY002SA1001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
148534,CY002SA1002,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
148535,CY002SA1003,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [26]:
outliers_df.to_excel("outputFiles/dl_outliers.xlsx")

In [27]:
wetchem_df = pd.read_csv("all_wetchem_data_uncleeaned_15-7-2022 (1).csv")

In [29]:
wetchem_df = wetchem_df.rename(columns={"Unnamed: 0":"sample_code"})

In [31]:
wetchem_df = wetchem_df.set_index("sample_code")

In [32]:
wetchem_df

,organic_carbon,total_nitrogen,aluminium,boron,calcium,copper,ec_salts,exchangeable_acidity,iron,magnesium,...,potassium,sodium,sulphur,zinc,cec,clay,sand,silt,phosphorus_olsen,reactive_carbon
sample_code,,,,,,,,,,,,,,,,,,,,,
AGD102-129SA0001,NaN,NaN,NaN,NaN,5730.0,NaN,NaN,NaN,NaN,856.0,...,646.0,169.0,NaN,NaN,40.065624,NaN,NaN,NaN,NaN,NaN
AGD102-130SA0001,NaN,NaN,NaN,2.89,1990.0,1.25,86.0,NaN,242.0,326.0,...,387.0,112.0,NaN,24.8,15.074521,NaN,NaN,NaN,NaN,NaN
AGD102-132SA0001,NaN,NaN,NaN,NaN,2850.0,NaN,NaN,NaN,NaN,717.0,...,208.0,218.0,NaN,NaN,26.810968,NaN,NaN,NaN,NaN,NaN
AGD102-133SA0001,NaN,NaN,NaN,NaN,283.0,NaN,NaN,NaN,NaN,47.6,...,103.0,21.6,NaN,NaN,3.085441,NaN,NaN,NaN,NaN,NaN
AGD102-133SA0002,NaN,NaN,NaN,NaN,1320.0,NaN,NaN,NaN,NaN,287.0,...,425.0,28.0,NaN,NaN,10.690643,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
CY001SA0091,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CY001SA0092,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CY002SA1001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CY002SA1002,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CY002SA1003,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [33]:
wetchem_df.to_csv("all_wetchem_transformed.csv")